import Head from "next/head";
import { useState, useRef } from "react";
import MyDataTable from "../dist";

export default function Home() {
  const tableRef = useRef();

  const columns = [
    {
      field: "name",
      title: "Name",
      searchable: true,
      sorting: true,
    },
    {
      field: "email",
      title: "Email",
      searchable: true,
    },
  ];

  const data = [
    { _id: "1", name: "John Doe", email: "john@example.com" },
    { _id: "2", name: "Jane Smith", email: "jane@example.com" },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`main`}>
        <MyDataTable
          title="Users"
          tableRef={tableRef}
          columns={columns}
          data={() => ({ data, page: 0, totalCount: 100 })}
          filterOptions={[
            {
              label: "Name",
              field: "name",
              type: "select",
              options: [
                {
                  label: "Option 1",
                  value: "option1",
                },
              ],
            },
          ]}
          options={{
            exportButton: true,
            refreshButton: true,
          }}
        />
      </main>
    </>
  );
}
